### ISSUE TITLE
CSS fehlerhaft

### ISSUE THREAD

**Issue by caspii** [caspii/flinkbox#10]
Hi, habe deine Änderungen deployt. Super! du hast ja noch einiges gemacht.

Jetzt sind einige Sachen krum und schief. Kannst du mal draufschauen? Zum Beispiel
- Das Grind bei http://flinkbox.de/percent.html#.VPAnIHXN_mE
- Außerdem kann man die Ergebnisse nicht mehr lesen, wenn man einmal auf berechnen geklickt hat

Thanx!

**Comment by hardwaresoftwork** [comment]
hat das vll. mit dem deployment zutun?
welchen browser (ie) ? :D

hab grad alles frisch gepulled... ?
http://192.168.1.61/flinkbox/percent.html#.VPQx13XN8YO
