### ISSUE TITLE
Lottozahlen Generator

### ISSUE THREAD

**Issue by caspii** [caspii/flinkbox#4]
For version 1, I think something like this is enough:http://www.umrechnung.org/zufalls-lotto-zahlen-generator/lottozahlen-generieren.htm

**Comment by hardwaresoftwork** [comment]
![lotto-1](https://cloud.githubusercontent.com/assets/760988/5992162/6d707f96-aa1c-11e4-9979-d9e314a6fca6.PNG)

![lotto-2](https://cloud.githubusercontent.com/assets/760988/5992163/6fda03a6-aa1c-11e4-8244-a55fcc25ebbe.PNG)

Algo:
http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by caspii** [comment]
Excellent! Deployed
